# Generated by Django 4.1.7 on 2023-03-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='image',
        ),
    ]
