# Generated by Django 4.1.7 on 2023-03-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_alter_articleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='Фото'),
        ),
    ]
