# Generated by Django 4.1.7 on 2023-05-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_alter_articleimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='image',
        ),
    ]
