# Generated by Django 4.1.7 on 2023-05-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0013_remove_articleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='photos', verbose_name='Фото'),
        ),
    ]
